import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import WorkCard from '../component/molcules/work/WorkCard'
import HomeLayout  from '../component/templates/HomeLayout'
import axios from "axios"
import { fetchData } from '../lib/post'

//import styles from '../styles/Home.module.css'

//SSG

export async function getStaticProps () {
  const response = await axios.get("http://localhost:5000/api/posts")
  const allPostsData=  response.data
  
  return {props:{allPostsData}}
}



export default function Home({allPostsData}) {

  //全てのpostをuseStateで持ってくる
  
  //const [posts, setPosts] = useState([])

  // useEffect(() => {
  //   const fetchPosts = async ()=>{
  //     try{
  //       const response = await axios.get("/posts")
        
  //       setPosts(response.data)
  //     }catch(err){
  //       console.log(err)
  //     }
      
  //   }

  //   fetchPosts()
  // }, [])

  


  return (
    <div >
      <Head>
        <title>okjm portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <HomeLayout>

      {allPostsData.map((post)=>{
        return(
          <WorkCard key={post.id} post={post} />
        )

      })}
      
      </HomeLayout>

     
    </div>
  )
}
  